[colors]

[colors.primary]
background = '#1b0c15'
foreground = '#fabab0'

[colors.normal]
black = "#1b0c15"
red = "#ef4e49"
green = "#d47193"
yellow = "#fabab0"
blue = "#52396e"
magenta = "#8e5282"
cyan = "#b9373b"
white = "#fabab0"

[colors.bright]
black = "#52396e"
red = "#ef4e49"
green = "#d47193"
yellow = "#fabab0"
blue = "#8e5282"
magenta = "#d47193"
cyan = "#b9373b"
white = "#fabab0"

[colors.cursor]
text = "#1b0c15"
cursor = "#ef4e49"

