[colors]

[colors.primary]
background = '#1b0c15'
foreground = '#fabab0'

[colors.normal]
black = "#1b0c15"
red = "#ef4e49"
green = "#d47193"
yellow = "#fabab0"
blue = "#4935ab"
magenta = "#d47193"
cyan = "#822226"
white = "#fabab0"

[colors.bright]
black = "#4935ab"
red = "#ef4e49"
green = "#d47193"
yellow = "#fabab0"
blue = "#4935ab"
magenta = "#d47193"
cyan = "#822226"
white = "#fabab0"

[colors.cursor]
text = "#1b0c15"
cursor = "#ef4e49"

